import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import WrapperLayout from '@/components/layouts/wrapper-layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={'en'}>
      <body className={inter.className}>
        <Providers>
          <WrapperLayout>{children}</WrapperLayout>
        </Providers>
      </body>
    </html>
  );
}
