import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import WrapperLayout from '@/components/layouts/wrapper-layout';
import userInitPersistData from "@/hooks/useInitPersistData";
import useDeviceCheck from "@/hooks/useDeviceCheck";
import useWalletEvents from "@/hooks/useWalletEvents";
import useChakraTheme from "@/hooks/useChakraTheme";
import useLoadWalletInstances from "@/hooks/useLoadWalletInstances";
import useWeb3Injected from "@/hooks/useWeb3Injected";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useWeb3Injected();
  useLoadWalletInstances();
  userInitPersistData();
  useChakraTheme();
  useWalletEvents();
  useDeviceCheck();

  return (
    <html lang={'en'}>
      <body className={inter.className}>
        <Providers>
          <WrapperLayout>{children}</WrapperLayout>
        </Providers>
      </body>
    </html>
  );
}
