import type { Metadata } from "next";
import WrapperLayout from "@/components/layouts/wrapper-layout";
import ClientProviders from "@/components/providers/ClientProviders";
// import useWalletEvents from "@/hooks/useWalletEvents";
// import useLoadWalletInstances from "@/hooks/useLoadWalletInstances";
// import useWeb3Injected from "@/hooks/useWeb3Injected";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang={'en'}>
      <body>
      {/*{children}*/}
        <ClientProviders>
          <WrapperLayout>
            {children}
          </WrapperLayout>
        </ClientProviders>
      </body>
    </html>
  );
}
