name: Deploy testing
run-name: ${{ github.actor }} is deploying testing branch🚀
on:
  push:
    branches:
      - 'testing'
jobs:
  Deploy:
    runs-on: [testing-mina-user-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.19
        uses: actions/setup-node@v2
        with:
          node-version: 18.19

      - run: |
          cp .env.example .env
          yarn
          yarn build
          pm2 restart testing.pm2.json
